### ISSUE TITLE
Downloads docker as dependency

### ISSUE THREAD

**Issue by MOZGIII** [tcnksm/ghr#36]
For some reason I end up downloading docker after calling `go get -v github.com/tcnksm/ghr`:

```
go get -v github.com/tcnksm/ghr
github.com/dotcloud/docker (download)
...
```

If you're using docker for testing or something, code should probably be decomposed into two parts - one being the actual app, and the other being what is needed to test/package it.

**Comment by tcnksm** [comment]
This is because I use `mflag` package in docker project. I should stop this.

**Comment by nathany** [comment]
If nothing else, shouldn't it be using "github.com/docker/docker/pkg/mflag" rather than the old dotcloud/docker?

What is the advantage of mflag over flag? It took a surprising amount of time to fetch ghr (133s).

```
❯ go get -u -v github.com/tcnksm/ghr 
github.com/tcnksm/ghr (download)
github.com/dotcloud/docker (download)
github.com/docker/docker (download)
github.com/opencontainers/runc (download)
github.com/google/go-github (download)
github.com/google/go-querystring (download)
github.com/mitchellh/colorstring (download)
github.com/tcnksm/go-gitconfig (download)
github.com/tcnksm/go-latest (download)
github.com/hashicorp/go-version (download)
Fetching https://golang.org/x/net/html?go-get=1
Parsing meta tags from https://golang.org/x/net/html?go-get=1 (status code 200)
get "golang.org/x/net/html": found meta tag main.metaImport{Prefix:"golang.org/x/net", VCS:"git", RepoRoot:"https://go.googlesource.com/net"} at https://golang.org/x/net/html?go-get=1
get "golang.org/x/net/html": verifying non-authoritative meta tag
Fetching https://golang.org/x/net?go-get=1
Parsing meta tags from https://golang.org/x/net?go-get=1 (status code 200)
golang.org/x/net (download)
Fetching https://golang.org/x/net/html/atom?go-get=1
Parsing meta tags from https://golang.org/x/net/html/atom?go-get=1 (status code 200)
get "golang.org/x/net/html/atom": found meta tag main.metaImport{Prefix:"golang.org/x/net", VCS:"git", RepoRoot:"https://go.googlesource.com/net"} at https://golang.org/x/net/html/atom?go-get=1
get "golang.org/x/net/html/atom": verifying non-authoritative meta tag
Fetching https://golang.org/x/oauth2?go-get=1
Parsing meta tags from https://golang.org/x/oauth2?go-get=1 (status code 200)
get "golang.org/x/oauth2": found meta tag main.metaImport{Prefix:"golang.org/x/oauth2", VCS:"git", RepoRoot:"https://go.googlesource.com/oauth2"} at https://golang.org/x/oauth2?go-get=1
golang.org/x/oauth2 (download)
Fetching https://golang.org/x/net/context?go-get=1
Parsing meta tags from https://golang.org/x/net/context?go-get=1 (status code 200)
get "golang.org/x/net/context": found meta tag main.metaImport{Prefix:"golang.org/x/net", VCS:"git", RepoRoot:"https://go.googlesource.com/net"} at https://golang.org/x/net/context?go-get=1
get "golang.org/x/net/context": verifying non-authoritative meta tag
Fetching https://golang.org/x/oauth2/internal?go-get=1
Parsing meta tags from https://golang.org/x/oauth2/internal?go-get=1 (status code 200)
get "golang.org/x/oauth2/internal": found meta tag main.metaImport{Prefix:"golang.org/x/oauth2", VCS:"git", RepoRoot:"https://go.googlesource.com/oauth2"} at https://golang.org/x/oauth2/internal?go-get=1
get "golang.org/x/oauth2/internal": verifying non-authoritative meta tag
Fetching https://golang.org/x/oauth2?go-get=1
Parsing meta tags from https://golang.org/x/oauth2?go-get=1 (status code 200)
github.com/opencontainers/runc/libcontainer/user
github.com/mitchellh/colorstring
github.com/tcnksm/go-gitconfig
github.com/google/go-github/github
github.com/hashicorp/go-version
golang.org/x/net/html/atom
golang.org/x/net/html
golang.org/x/net/context
github.com/docker/docker/pkg/homedir
github.com/dotcloud/docker/pkg/mflag
golang.org/x/oauth2/internal
golang.org/x/oauth2
github.com/tcnksm/go-latest
github.com/tcnksm/ghr
```

**Comment by nathany** [comment]
It takes ~32 seconds to fetch and build ghr on CircleCI, compared to the ~1 second to fetch and build golint or the ~2 seconds it take to build my binary and ~2 seconds it takes to upload it to GitHub.

While I don't know how much of that is related to the decision to use mflag instead of flag, I'm going to need to introduce some caching for the ghr binary.

**Comment by nathany** [comment]
You should be able to vendor the mflag package in your repository without the rest of docker and its dependencies.

Doing so will require Go 1.6 or Go 1.5 with GO15VENDOREXPERIMENT=1 when building.

Of course people could just download the binaries that you've provided instead of building from source.

**Comment by tcnksm** [comment]
> While I don't know how much of that is related to the decision to use mflag instead of flag, I'm going to need to introduce some caching for the ghr binary.

`ghr` is one of my initial project of golang and at that time I preferred using `--` instead of `-` for option and I felt it was easy to handle short/long option. 

Now I prefer using just `flag` and want to replace it with `mflag`. But it breaks interface  of `ghr` ( e.g., `ghr --verision` to `ghr -version`). I know some user uses `ghr` on CI/CD and this may break their script. So I can not replace it now (should migrate in future).

To solve this problem now I've create PR for vendoring docker `mflag` :), https://github.com/tcnksm/ghr/pull/38 

I'll merge it soon so please try it. Thanks

**Comment by tcnksm** [comment]
@MOZGIII Sorry for late fixing

**Comment by nathany** [comment]
Thanks Taichi. I'll give it a try.
